version: 2

models:
  - name: int_order_items_joined
    columns:
      - name: order_item_key
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null

  - name: int_customer_orders
    description: "Agregation per customer — total orders, spend, segment"
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: total_orders
        tests:
          - not_null